### ISSUE TITLE
TG 4.16.8

### ISSUE THREAD

**Issue by Sidiusz** [kirsan31/tdesktop#1]
### Is your feature request related to a problem?

Hi! Any plans for 4.16.8?

### Describe the solution you'd like

/

### Describe alternatives you've considered

.

### Additional context

.

**Comment by kirsan31** [comment]
You mean binary release (because code for 4.16.8 already merged)?

**Comment by Sidiusz** [comment]
> You mean binary release (because code for 4.16.8 already merged)?

Sort of, yeah, I guess
It's just that they've added a lot of new stuff in the new versions, and I can't live without wide messages

**Comment by kirsan31** [comment]
Done. I didn’t think that anyone other than me and my friends needed binaries :)

**Comment by Sidiusz** [comment]
Thank you very much! I fckin love you
